### ISSUE TITLE
Armor descriptions not registered carriage returns.

### ISSUE THREAD

**Issue by Thuckenstein** [drewg13/foundryvtt-openlegends#1]
If you enter a description for armor type equipment, it won't format properly and continues on past the side of the window. If the description is long enough you can no longer edit the description at all, since the text pushes the edit button off the side of screen where it doesn't appear. (I hope that makes sense.)

**Comment by drewg13** [comment]
Can you provide a screenshot of what you're seeing?  Is this only in armor types or does it happen with other types?

**Comment by drewg13** [comment]
I think this was fixed in version 3.1
