### ISSUE TITLE
NPC Sheet: Max HP always defaulting to 10

### ISSUE THREAD

**Issue by Thuckenstein** [drewg13/foundryvtt-openlegends#2]
On the NPC Sheet, the background of Max HP is red and value defaults to 10.
It can be changed, but keeps defaulting back to 10 if a new token is dragged to another window (actors, compendium etc...)

I suspect it's not calculating properly for some reason, but I shouldn't I be able to enter any value and have it stay that way?

![max_hp_error](https://github.com/drewg13/foundryvtt-openlegends/assets/101313341/c58a8339-76b5-46ea-ae3c-2ebfa5b14087)

**Comment by drewg13** [comment]
Should be fixed in 3.1.1

**Comment by drewg13** [comment]
It wasn't saving properly to the database as a result of the V9->V10 syntax shift.  As far as I can tell, it's not independently calculated the way PC MaxHP is, so it's just a floating variable like any other NPC stat.  The red background also appears to be intentional for that field specifically.

**Comment by JacobfromAVS** [comment]
This is fixed. 
![image](https://github.com/drewg13/foundryvtt-openlegends/assets/141856425/d3d16b2b-0be7-404e-9d51-791f1604fc45)
