### ISSUE TITLE
Lethal damage Cap

### ISSUE THREAD

**Issue by JacobfromAVS** [drewg13/foundryvtt-openlegends#3]
Lethal damage does not cap at 10. It should cap at the max HP of the character. The rest of lethal damage is working as it supposed to.

**Comment by drewg13** [comment]
This is more complicated than I thought.  It might take a minute to figure it out.  The method previously used to set caps and controls is causing some of these issues and it's hard to tell how it's supposed to work.

**Comment by drewg13** [comment]
Hahahahaha, no it was much simpler.  The hp.lethal was dependent on hp.max as an upper limit, but the hp.max calculation came after the hp.lethal calculation, so it defaulted to 10.  In the process, I found a different issue where setting the attributes in the cog popup window isn't always sticking, so I'll work that one out before releasing.

**Comment by drewg13** [comment]
I think I got it all, should be in the next version.
