### ISSUE TITLE
Add weapons, armor, and equipment compendium

### ISSUE THREAD

**Issue by JacobfromAVS** [drewg13/foundryvtt-openlegends#4]
Here is the compendiums of open-legend equipment that I made. This really needs to be part of the core module for OpenLegend. These are all pulled from the book itself. 

[ForgeVTT-export-forge-vtt-shared-compendiums-ol-equipment-2023-04-13_19_20_10.zip](https://github.com/drewg13/foundryvtt-openlegends/files/14483247/ForgeVTT-export-forge-vtt-shared-compendiums-ol-equipment-2023-04-13_19_20_10.zip)

**Comment by drewg13** [comment]
I've got these added for the next release, no issues.
