### ISSUE TITLE
QoL: Banes and Boons.

### ISSUE THREAD

**Issue by JacobfromAVS** [drewg13/foundryvtt-openlegends#6]
It would be nice to have the banes and boons as conditions you could put on the tokens. so renaming some of these to fit the banes and boons would probably be the simple way. 

![image](https://github.com/drewg13/foundryvtt-openlegends/assets/141856425/67070157-30f1-4e5e-84b2-8f29b2a476fe)

**Comment by drewg13** [comment]
Easily doable, but it will take a minute to get it done.  Would you want a total replacement of these, meaning only things listed as Boons or Banes present here?  Are you happy with the icons currently assigned to all of the Boons and Banes?

**Comment by JacobfromAVS** [comment]
I think only boon and banes need to be here. That is all these is in this system. The current icons are fine.

**Comment by drewg13** [comment]
![image](https://github.com/drewg13/foundryvtt-openlegends/assets/1455026/72aa11e1-d1cf-479a-ae1f-40a03b2b5030)

That's... pretty substantial.  What do you think?

**Comment by JacobfromAVS** [comment]
Wow. That is a lot but it really makes sense per the system.  Unless you
were make it a drag and drop thing like pathfinder2e, but I think that this
way is pretty easy.  I think this is the simplest way to do it.

**Comment by drewg13** [comment]
![image](https://github.com/drewg13/foundryvtt-openlegends/assets/1455026/670f7058-516e-4520-af0a-bc9232e02190)

Works for me.  I tweaked it to change the backgrounds to transparent and to add back the "Dead" condition for integration with the combat tracker.  Also, it's programmatic, meaning the system grabs all the boons and banes and shoves them in there automatically, so I don't have to maintain and update a separate list of them just for this purpose and, if you add more of your own, they'll get included automatically.

This will show up in the next release.
