### ISSUE TITLE
Defend action toggle. 

### ISSUE THREAD

**Issue by JacobfromAVS** [drewg13/foundryvtt-openlegends#8]
Something that indicates that the player used a defend action. It would be really cool that if on their turn a little warning of you used a defend action popped up. I am not sure how to do that though

**Comment by drewg13** [comment]
So, if I'm understanding the system correctly, there look to me like three good ways to go about this:
1.  Provide a simple "Used Defend Action" toggle that hooks into the combat tracker and resets at the beginning of the player's next turn, perhaps also with a warning about Major Action use that toggles off at the end of the player's next turn.
2.  Hooking into the chat cards to provide a Defend option when a player is attacked and then hooking into the combat tracker to trigger a reminder at the beginning of that player's next turn.
3.  Going deeper and tracking the use of Major, Minor, Move, and Focus actions during each combat round, similar to how the Year Zero Actions module works perhaps.

Option 1 would be pretty simple, I think.  Option 2 would be a bit more involved and might take me a while.  Option 3 would be a major addition to the system and would require a lot of work.

Let me know what you think.

**Comment by JacobfromAVS** [comment]
1 would work just fine. 2 sounds nice, and i know that the pathfinder 2e reaction checker module does something like that and maybe we could pull from that. I think 3 is to much right now .

**Comment by drewg13** [comment]
Right, I played around with option 1 over the weekend and think I came up with a decent solution.  One important question though, do NPCs use Defend actions and/or do you want them to be able to make use of the same system?  As of right now, I have it set to only work for PCs and the complications inherent to unlinked token NPCs in Foundry would require a bit more work.

**Comment by JacobfromAVS** [comment]
Everyone can use defend action.

**Comment by drewg13** [comment]
OK, figured it out.  This will be included in the next release.

You're going to want to test this out a bit before using it live.  Here's how it works:
1.  You won't see anything new until a character is in combat, ie listed on the Combat Tracker
2.  Once they're in combat, you'll see a toggle at the top of the Actions section like so:   
![image](https://github.com/drewg13/foundryvtt-openlegends/assets/1455026/b16371e1-6421-4be9-8097-697f4fd9ca2d)
3.  Hovering over the toggle will show a tooltip indicating that it's for "Interrupt Action Used?".
3.  The toggle will reset to off at the beginning of that character's combat turn, so toggling it outside their turn will be ignored.
4.  If, during their turn, they use an Interrupt Action (Defend or Improvise), they will need to remember to toggle it like so:  
![image](https://github.com/drewg13/foundryvtt-openlegends/assets/1455026/087acaca-8d11-4b4a-8853-a47eba2c5bb2)
5.  At the end of their turn/beginning of the next character's combat turn, this reminder will show:  
![image](https://github.com/drewg13/foundryvtt-openlegends/assets/1455026/5340545f-85b0-414f-8844-e14a3796d31f)
6.  At the beginning of their next turn, the toggle will reset, but the reminder will remain through the end of their turn.
7.  At the end of their turn the reminder will disappear, unless the toggle was activated again that turn.
8.  Once the Combat is ended, everything clears and the toggle will no longer be visible.

Hopefully that all makes sense and follows a reasonable and useful path.  Let me know what you think and if any changes are needed.
