### ISSUE TITLE
QOL, add the heromuster filter to NPC

### ISSUE THREAD

**Issue by JacobfromAVS** [drewg13/foundryvtt-openlegends#9]
I am loving the HeroMuster Filter on the character sheets, Could we add them to NPC's too. That will make character creation and using NPC's a little easier for the GM.

**Comment by JacobfromAVS** [comment]
They use mostly the same Feats as the player characters, There are some that are GM only but you can drag and drop them on the character sheet. The banes and boons would be huge.

**Comment by drewg13** [comment]
Makes sense, it's a super easy change to make.

**Comment by drewg13** [comment]
Added in 3.6.1
